name:                tensors
version:             0.1.2
synopsis:            Tensor in Haskell
description:         Tensor use type level programming in haskell.
homepage:            https://github.com/leptonyu/tensors#readme
license:             BSD3
author:              Daniel YU
maintainer:          Daniel YU <leptonyu@gmail.com>
copyright:           (c) 2018 Daniel YU
category:            Library
extra-source-files:
- README.md

ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -fno-warn-orphans -fno-warn-missing-signatures

default-extensions:
  - AllowAmbiguousTypes
  - DataKinds
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - KindSignatures
  - MultiParamTypeClasses
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances

dependencies:
  - base >= 4.7 && < 5
  - vector >=0.12.0.2 && <0.13
  - singletons >=2.4.1 && <2.6
  - reflection >=2.1.4 && <2.2
  - deepseq

library:
  source-dirs: src
  exposed-modules:
    - Data.Tensor
  other-modules:
    - Data.Tensor.Type
    - Data.Tensor.Index
    - Data.Tensor.Tensor
    - Data.Tensor.Matrix
    - Data.Tensor.Space
    - Data.Tensor.Statistics
tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
      - QuickCheck >=2.11.1 && <2.13
      - reflection >=2.1.4 && <2.2
benchmarks:
  bm:
    main: Bench.hs
    source-dirs:
      - bench
      - src
    dependencies:
      - criterion