name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  runhaskell:
    name: Hi tensors
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
    - uses: haskell/actions/setup@v2
      with:
        ghc-version: '8.10.3'
        cabal-version: '3.2'
    - name: Cache
      uses: actions/cache@v4
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Run
      run: |
       cabal v2-update
       cabal v2-build all
       cabal v2-test --enable-test all
       cabal v2-bench --enable-bench all