name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  runhaskell:
    name: Hi tensors
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10.3'
        cabal-version: '3.2'
    - name: Run
      run: |
       cabal v2-update
       cabal v2-build all
       cabal v2-test --enable-test all
       cabal v2-bench --enable-bench all